"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
type Question={id:string;label:string;type:"short_text"|"long_text"|"email"|"single_choice"|"multi_choice"|"rating";required:boolean;options:string[]};
type Survey={slug:string;version:number;title:string;description:string;questions:Question[];success_message:string};
export default function PublicSurvey({slug}:{slug:string}){
 const [survey,setSurvey]=useState<Survey|null>(null),[answers,setAnswers]=useState<Record<string,string|string[]|number>>({}),[step,setStep]=useState(0),[privacy,setPrivacy]=useState(false),[website,setWebsite]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState(""),[sending,setSending]=useState(false);const started=useRef(new Date().toISOString());const replay=useRef("");
 useEffect(()=>{let cancelled=false;void fetch(`/v1/public/surveys/${encodeURIComponent(slug)}`,{credentials:"omit"}).then(async response=>{const body=await response.json() as {survey?:Survey;error?:string};if(!cancelled){if(!response.ok||!body.survey)setError(body.error||"This survey is not available.");else setSurvey(body.survey)}}).catch(()=>{if(!cancelled)setError("This survey could not be loaded.")});return()=>{cancelled=true}},[slug]);
 const question=survey?.questions[step];const answered=question?question.type==="multi_choice"?Array.isArray(answers[question.id])&&Boolean((answers[question.id] as string[]).length):answers[question.id]!==undefined&&answers[question.id]!=="":false;
 async function submit(event:FormEvent){event.preventDefault();if(!survey)return;if(step<survey.questions.length-1){if(question?.required&&!answered){setError("Answer this question before continuing.");return}setError("");setStep(step+1);return}if(question?.required&&!answered){setError("Answer this question before continuing.");return}if(!privacy){setError("Privacy acknowledgement is required.");return}replay.current||=`survey:${crypto.randomUUID()}`;setSending(true);setError("");try{const response=await fetch(`/v1/public/surveys/${encodeURIComponent(slug)}/responses`,{method:"POST",headers:{"content-type":"application/json"},credentials:"omit",body:JSON.stringify({answers,privacy_accepted:privacy,started_at:started.current,website,idempotency_key:replay.current})});const body=await response.json() as {error?:string;success_message?:string};if(!response.ok)throw new Error(body.error||"Response could not be recorded.");setSuccess(body.success_message||survey.success_message)}catch(cause){setError(cause instanceof Error?cause.message:"Response could not be recorded.")}finally{setSending(false)}}
 const setAnswer=(value:string|string[]|number)=>question&&setAnswers({...answers,[question.id]:value});
 return <main className="survey-page"><section className="survey-shell"><header><span>OPENOPERATOR / RESEARCH</span><i>{survey?`V${survey.version}`:"…"}</i></header>{success?<div className="survey-success" role="status"><b>✓</b><h1>Response recorded.</h1><p>{success}</p></div>:<><div className="survey-intro"><p>FIELD STUDY</p><h1>{survey?.title||"Loading survey…"}</h1><p>{survey?.description}</p></div>{error&&<div className="survey-error" role="alert">{error}</div>}{survey&&question&&<form onSubmit={submit}><div className="survey-progress"><span>QUESTION {step+1} / {survey.questions.length}</span><i><b style={{width:`${(step+1)/survey.questions.length*100}%`}}/></i></div><fieldset><legend>{question.label}{question.required&&<b> REQUIRED</b>}</legend><QuestionInput question={question} value={answers[question.id]} onChange={setAnswer}/></fieldset>{step===survey.questions.length-1&&<label className="survey-privacy"><input type="checkbox" required checked={privacy} onChange={event=>setPrivacy(event.target.checked)}/><span>I acknowledge that my answers will be stored for aggregate analysis and individual response review. No marketing consent is requested. <b>Required.</b></span></label>}<input className="form-honeypot" tabIndex={-1} aria-hidden="true" value={website} onChange={event=>setWebsite(event.target.value)}/><div className="survey-actions">{step>0&&<button type="button" onClick={()=>{setStep(step-1);setError("")}}>← BACK</button>}<button disabled={sending}>{sending?"RECORDING…":step===survey.questions.length-1?"SUBMIT RESPONSE":"NEXT →"}</button></div><small>One immutable response is tied to the exact published survey version.</small></form>}</>}</section></main>
}
function QuestionInput({question,value,onChange}:{question:Question;value:unknown;onChange:(value:string|string[]|number)=>void}){if(question.type==="long_text")return <textarea autoFocus maxLength={4000} value={String(value||"")} onChange={event=>onChange(event.target.value)}/>;if(question.type==="short_text"||question.type==="email")return <input autoFocus type={question.type==="email"?"email":"text"} maxLength={question.type==="email"?254:500} value={String(value||"")} onChange={event=>onChange(event.target.value)}/>;if(question.type==="rating")return <div className="survey-rating">{[1,2,3,4,5].map(rating=><button type="button" className={value===rating?"selected":""} key={rating} onClick={()=>onChange(rating)}>{rating}<small>{rating===1?"LOW":rating===5?"HIGH":""}</small></button>)}</div>;return <div className="survey-options">{question.options.map(option=>{const selected=question.type==="multi_choice"?Array.isArray(value)&&value.includes(option):value===option;return <label key={option}><input type={question.type==="multi_choice"?"checkbox":"radio"} name={question.id} checked={selected} onChange={()=>onChange(question.type==="multi_choice"?(selected?(value as string[]).filter(item=>item!==option):[...(Array.isArray(value)?value:[]),option]):option)}/><span>{option}</span></label>})}</div>}
