"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Rule = { day_of_week: number; start_minute: number; end_minute: number };
type Calendar = { id:string; name:string; slug:string; status:"draft"|"published"|"revoked"; title:string; description:string; timezone:string; duration_minutes:number; buffer_before_minutes:number; buffer_after_minutes:number; minimum_notice_minutes:number; maximum_days_ahead:number; revision:number; availability:Rule[]; public_path:string|null; appointment_count?:number };
type Appointment = { id:string; name:string; email:string; starts_at:string; status:string; sync_status:string };
const days = ["SUN","MON","TUE","WED","THU","FRI","SAT"];
async function api<T>(path:string, init?:RequestInit) { const response=await fetch(path,{credentials:"include",...init}); const body=await response.json() as T&{error?:string}; if(!response.ok) throw new Error(body.error||`Request failed (${response.status})`); return body; }
const clock=(value:number)=>`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`;
const minutes=(value:string)=>{const [hour,minute]=value.split(":").map(Number);return hour*60+minute;};

export default function BookingWorkspace({active,canAdmin}:{active:boolean;canAdmin:boolean}) {
  const [calendars,setCalendars]=useState<Calendar[]>([]), [selectedId,setSelectedId]=useState(""), [draft,setDraft]=useState<Calendar|null>(null), [appointments,setAppointments]=useState<Appointment[]>([]);
  const [creating,setCreating]=useState(false), [newName,setNewName]=useState(""), [newTitle,setNewTitle]=useState(""), [newTimezone,setNewTimezone]=useState("UTC");
  const [working,setWorking]=useState(""), [error,setError]=useState(""), [notice,setNotice]=useState(""), [armed,setArmed]=useState("");
  const selected=useMemo(()=>calendars.find((calendar)=>calendar.id===selectedId),[calendars,selectedId]);
  const load=useCallback(async()=>{const data=await api<{calendars:Calendar[]}>("/v1/admin/booking-calendars");setCalendars(data.calendars);setSelectedId((current)=>current&&data.calendars.some((calendar)=>calendar.id===current)?current:data.calendars[0]?.id||"");},[]);
  useEffect(()=>{if(!active)return;const timer=setTimeout(()=>void load().catch((cause)=>setError(cause.message)),0);return()=>clearTimeout(timer);},[active,load]);
  useEffect(()=>{if(!active||!selectedId)return;let cancelled=false;void Promise.all([api<{calendar:Calendar}>(`/v1/admin/booking-calendars/${selectedId}`),api<{appointments:Appointment[]}>(`/v1/admin/booking-calendars/${selectedId}/appointments`)]).then(([detail,ledger])=>{if(!cancelled){setDraft(detail.calendar);setAppointments(ledger.appointments);}}).catch((cause)=>{if(!cancelled)setError(cause.message);});return()=>{cancelled=true;};},[active,selectedId]);
  async function create(event:FormEvent){event.preventDefault();setWorking("create");try{const data=await api<{calendar:Calendar}>("/v1/admin/booking-calendars",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:newName,title:newTitle,timezone:newTimezone})});setCreating(false);await load();setSelectedId(data.calendar.id);setNotice("Draft calendar created.");}catch(cause){setError(cause instanceof Error?cause.message:"Calendar could not be created");}finally{setWorking("");}}
  async function save(){if(!draft)return;setWorking("save");setError("");try{const data=await api<{calendar:Calendar}>(`/v1/admin/booking-calendars/${draft.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:draft.name,title:draft.title,description:draft.description,timezone:draft.timezone,duration_minutes:draft.duration_minutes,buffer_before_minutes:draft.buffer_before_minutes,buffer_after_minutes:draft.buffer_after_minutes,minimum_notice_minutes:draft.minimum_notice_minutes,maximum_days_ahead:draft.maximum_days_ahead,availability:draft.availability,if_revision:draft.revision})});setDraft(data.calendar);await load();setNotice("Availability saved.");}catch(cause){setError(cause instanceof Error?cause.message:"Calendar could not be saved");}finally{setWorking("");}}
  async function lifecycle(action:"publish"|"revoke"){if(!draft)return;if(armed!==action){setArmed(action);return;}setWorking(action);try{const data=await api<{calendar:Calendar}>(`/v1/admin/booking-calendars/${draft.id}/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({if_revision:draft.revision,confirmation:action==="publish"?"PUBLISH CALENDAR":"REVOKE CALENDAR"})});setDraft(data.calendar);setArmed("");await load();setNotice(action==="publish"?"Public booking is live.":"Public booking revoked.");}catch(cause){setError(cause instanceof Error?cause.message:"Lifecycle action failed");}finally{setWorking("");}}
  function setRule(day:number,field:"start_minute"|"end_minute"|"enabled",value:number|boolean){if(!draft)return;const existing=draft.availability.find((rule)=>rule.day_of_week===day);let availability=draft.availability.filter((rule)=>rule.day_of_week!==day);if(field==="enabled"?value:true)availability=[...availability,{day_of_week:day,start_minute:field==="start_minute"?Number(value):existing?.start_minute??540,end_minute:field==="end_minute"?Number(value):existing?.end_minute??1020}].sort((a,b)=>a.day_of_week-b.day_of_week);setDraft({...draft,availability});}
  if(!active)return null;
  return <main className="booking-workspace"><header className="forms-hero"><div><p className="eyebrow">TIME INVENTORY / LOCAL-FIRST</p><h1>Booking</h1><p>Publish controlled availability, prevent double-booking, and keep every appointment in a reviewable ledger.</p></div>{canAdmin&&<button onClick={()=>setCreating(true)}>NEW CALENDAR</button>}</header>
    {error&&<div className="conversation-banner error" role="alert">{error}</div>}{notice&&<div className="conversation-banner success" role="status">{notice}</div>}
    {creating&&<form className="form-create-strip" onSubmit={create}><label>INTERNAL NAME<input required value={newName} onChange={(event)=>setNewName(event.target.value)}/></label><label>PUBLIC TITLE<input required value={newTitle} onChange={(event)=>setNewTitle(event.target.value)}/></label><label>TIMEZONE<input required value={newTimezone} onChange={(event)=>setNewTimezone(event.target.value)}/></label><button disabled={working==="create"}>CREATE DRAFT</button><button type="button" className="secondary" onClick={()=>setCreating(false)}>CANCEL</button></form>}
    <div className="forms-layout"><aside className="forms-index"><header><b>CALENDAR REGISTER</b><small>{calendars.length} total</small></header>{calendars.map((calendar)=><button key={calendar.id} className={calendar.id===selectedId?"active":""} onClick={()=>setSelectedId(calendar.id)}><span><b>{calendar.name}</b><mark className={calendar.status}>{calendar.status}</mark></span><small>{calendar.appointment_count||0} active · rev {calendar.revision}</small></button>)}{!calendars.length&&<div className="empty-state">No calendars yet.</div>}</aside>
      <section className="form-blueprint">{draft&&selected?<><header><div><p>CALENDAR / {draft.slug}</p><h2>{draft.name}</h2></div><mark className={draft.status}>{draft.status}</mark></header><div className="form-editor">
        <label>INTERNAL NAME<input disabled={!canAdmin} value={draft.name} onChange={(event)=>setDraft({...draft,name:event.target.value})}/></label><label>PUBLIC TITLE<input disabled={!canAdmin} value={draft.title} onChange={(event)=>setDraft({...draft,title:event.target.value})}/></label><label className="wide">DESCRIPTION<textarea disabled={!canAdmin} value={draft.description} onChange={(event)=>setDraft({...draft,description:event.target.value})}/></label><label>TIMEZONE<input disabled={!canAdmin} value={draft.timezone} onChange={(event)=>setDraft({...draft,timezone:event.target.value})}/></label>
        <label>DURATION<select disabled={!canAdmin} value={draft.duration_minutes} onChange={(event)=>setDraft({...draft,duration_minutes:Number(event.target.value)})}>{[15,30,45,60,90,120].map((value)=><option key={value}>{value}</option>)}</select></label>{[["BUFFER BEFORE","buffer_before_minutes",120],["BUFFER AFTER","buffer_after_minutes",120],["MINIMUM NOTICE","minimum_notice_minutes",43200],["BOOKING HORIZON","maximum_days_ahead",365]].map(([label,key,max])=><label key={String(key)}>{label}<input disabled={!canAdmin} type="number" min="0" max={Number(max)} value={Number(draft[key as keyof Calendar])} onChange={(event)=>setDraft({...draft,[key]:Number(event.target.value)})}/></label>)}
        <fieldset className="wide booking-rules"><legend>WEEKLY AVAILABILITY</legend>{days.map((name,day)=>{const rule=draft.availability.find((candidate)=>candidate.day_of_week===day);return <div key={name}><label><input type="checkbox" disabled={!canAdmin} checked={Boolean(rule)} onChange={(event)=>setRule(day,"enabled",event.target.checked)}/> {name}</label><input aria-label={`${name} start`} type="time" disabled={!canAdmin||!rule} value={clock(rule?.start_minute??540)} onChange={(event)=>setRule(day,"start_minute",minutes(event.target.value))}/><span>TO</span><input aria-label={`${name} end`} type="time" disabled={!canAdmin||!rule} value={clock(rule?.end_minute??1020)} onChange={(event)=>setRule(day,"end_minute",minutes(event.target.value))}/></div>;})}</fieldset>
        <div className="wide form-actions">{canAdmin&&<button onClick={()=>void save()} disabled={Boolean(working)}>SAVE AVAILABILITY</button>}{canAdmin&&draft.status!=="published"&&<button className="publish" onClick={()=>void lifecycle("publish")}>{armed==="publish"?"CONFIRM PUBLISH":"PUBLISH"}</button>}{canAdmin&&draft.status==="published"&&<button className="danger" onClick={()=>void lifecycle("revoke")}>{armed==="revoke"?"CONFIRM REVOKE":"REVOKE"}</button>}{draft.public_path&&<a href={draft.public_path} target="_blank" rel="noreferrer">OPEN PUBLIC PAGE ↗</a>}</div></div>
        <section className="booking-ledger"><header><b>APPOINTMENT LEDGER</b><small>{appointments.length} records</small></header>{appointments.map((appointment)=><article key={appointment.id}><time>{new Date(appointment.starts_at).toLocaleString([],{timeZone:draft.timezone})}</time><span><b>{appointment.name}</b><small>{appointment.email}</small></span><mark>{appointment.status}</mark><small>{appointment.sync_status}</small></article>)}{!appointments.length&&<div className="empty-state">No appointments recorded.</div>}</section></>:<div className="empty-state">Choose or create a calendar.</div>}</section></div>
  </main>;
}
