"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Campaign = { id: string; name: string; status: "draft" | "ready" | "sending" | "completed" | "cancelled"; subject: string; body_text: string; contact_ids: string[]; revision: number; version_count?: number; recipient_count?: number; accepted_count?: number; failed_count?: number };
type Contact = { id: string; email: string; first_name: string | null; last_name: string | null; consent_status: string | null; consent_basis: string | null };
type Recipient = { id: string; email: string; first_name: string | null; last_name: string | null; status: string; attempt_count: number; provider_email_id: string | null; response_status: number | null; error: string | null; sent_at: string | null };
type Version = { id: string; version: number; exclusion_summary: { selected: number; eligible: number; excluded: number; reasons: Record<string, number> }; published_by: string; published_at: string };
async function api<T>(path: string, init?: RequestInit) { const response = await fetch(path, { credentials: "include", ...init }); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; }

export default function MarketingWorkspace({ active, canAdmin }: { active: boolean; canAdmin: boolean }) {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]), [selectedId, setSelectedId] = useState(""), [draft, setDraft] = useState<Campaign | null>(null), [contacts, setContacts] = useState<Contact[]>([]), [recipients, setRecipients] = useState<Recipient[]>([]), [versions, setVersions] = useState<Version[]>([]), [connection, setConnection] = useState<{ label: string; from_email: string } | null>(null), [signing, setSigning] = useState(false), [creating, setCreating] = useState(false), [name, setName] = useState(""), [working, setWorking] = useState(""), [armed, setArmed] = useState(""), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const load = useCallback(async () => { const data = await api<{ campaigns: Campaign[] }>("/v1/admin/marketing-campaigns"); setCampaigns(data.campaigns); setSelectedId((current) => current && data.campaigns.some((campaign) => campaign.id === current) ? current : data.campaigns[0]?.id || ""); }, []);
  const loadDetail = useCallback(async (id: string) => { const data = await api<{ campaign: Campaign; contacts: Contact[]; recipients: Recipient[]; versions: Version[]; connection: { label: string; from_email: string } | null; runtime: { unsubscribe_signing_configured: boolean } }>(`/v1/admin/marketing-campaigns/${id}`); setDraft(data.campaign); setContacts(data.contacts); setRecipients(data.recipients); setVersions(data.versions); setConnection(data.connection); setSigning(data.runtime.unsubscribe_signing_configured); }, []);
  useEffect(() => { if (!active) return; const timer = setTimeout(() => void load().catch((cause) => setError(cause.message)), 0); return () => clearTimeout(timer); }, [active, load]);
  useEffect(() => { if (!active || !selectedId) return; void loadDetail(selectedId).catch((cause) => setError(cause.message)); }, [active, selectedId, loadDetail]);
  const selectedContacts = useMemo(() => new Set(draft?.contact_ids || []), [draft?.contact_ids]);
  async function create(event: FormEvent) { event.preventDefault(); setWorking("create"); setError(""); try { const data = await api<{ campaign: Campaign }>("/v1/admin/marketing-campaigns", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }) }); setName(""); setCreating(false); await load(); setSelectedId(data.campaign.id); setNotice("Campaign draft created. Nothing has been sent."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Campaign could not be created"); } finally { setWorking(""); } }
  async function save() { if (!draft) return; setWorking("save"); setError(""); try { const data = await api<{ campaign: Campaign }>(`/v1/admin/marketing-campaigns/${draft.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: draft.name, subject: draft.subject, body_text: draft.body_text, contact_ids: draft.contact_ids, if_revision: draft.revision }) }); setDraft(data.campaign); await load(); setNotice("Draft saved. No recipient snapshot or email changed."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Campaign could not be saved"); } finally { setWorking(""); } }
  async function lifecycle(action: "publish" | "launch" | "retry" | "cancel") { if (!draft) return; if (armed !== action) { setArmed(action); return; } const confirmation = { publish: "FREEZE RECIPIENTS", launch: "SEND CAMPAIGN", retry: "RETRY FAILED RECIPIENTS", cancel: "CANCEL CAMPAIGN" }[action]; setWorking(action); setError(""); try { const data = await api<{ campaign: Campaign }>(`/v1/admin/marketing-campaigns/${draft.id}/${action}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ if_revision: draft.revision, confirmation }) }); setArmed(""); await load(); await loadDetail(draft.id); setNotice(action === "publish" ? "Recipient V1 frozen from current express-consent evidence." : action === "launch" ? "Bounded send finished. Review recipient evidence below." : action === "retry" ? "Failed, still-consented recipients were retried once." : "Unsent recipients were cancelled. Provider-accepted email cannot be recalled."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Campaign lifecycle failed"); } finally { setWorking(""); } }
  function toggleContact(contactId: string) { if (!draft || draft.status !== "draft") return; setDraft({ ...draft, contact_ids: selectedContacts.has(contactId) ? draft.contact_ids.filter((id) => id !== contactId) : [...draft.contact_ids, contactId].slice(0, 25) }); setArmed(""); }
  if (!active) return null;
  const latestVersion = versions[0]; const failed = recipients.filter((recipient) => recipient.status === "failed").length;
  return <main className="marketing-workspace"><header className="marketing-hero"><div><p>CONSENT-AWARE EMAIL OPERATIONS</p><h1>Marketing</h1><span>Freeze a small express-consent audience, send through your verified Resend connection, and retain recipient-level proof. Provider acceptance is not delivery or an open.</span></div>{canAdmin && <button onClick={() => setCreating(true)}>NEW CAMPAIGN</button>}</header>
    {error && <div className="conversation-banner error">{error}</div>}{notice && <div className="conversation-banner">{notice}</div>}
    {creating && <form className="marketing-create" onSubmit={create}><label>INTERNAL CAMPAIGN NAME<input required maxLength={120} value={name} onChange={(event) => setName(event.target.value)}/></label><button disabled={working === "create"}>CREATE DRAFT</button><button type="button" onClick={() => setCreating(false)}>CANCEL</button></form>}
    <div className="marketing-layout"><aside className="marketing-register"><header><b>CAMPAIGNS</b><small>{campaigns.length} total</small></header>{campaigns.map((campaign) => <button key={campaign.id} className={campaign.id === selectedId ? "active" : ""} onClick={() => setSelectedId(campaign.id)}><b>{campaign.name}</b><span>{campaign.status} · {campaign.accepted_count || 0} accepted · {campaign.failed_count || 0} failed</span></button>)}{!campaigns.length && <p>No campaigns yet.</p>}</aside>
      <section className="marketing-studio">{draft ? <><header><div><p>ONE-TIME CAMPAIGN</p><h2>{draft.name}</h2></div><mark>{draft.status}</mark></header><div className="marketing-boundary"><b>AUTHORITY BOUNDARY</b><span>{connection ? `${connection.label} · ${connection.from_email}` : "No active Resend sender"}</span><small>{signing ? "One-click unsubscribe signing is configured." : "Unsubscribe signing is missing; recipient freezing is blocked."} HTML, tracking, schedules, social publishing, and unlimited sends are absent.</small></div>
        <div className="marketing-editor"><label>INTERNAL NAME<input disabled={!canAdmin || draft.status !== "draft"} maxLength={120} value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })}/></label><label>SUBJECT<input disabled={!canAdmin || draft.status !== "draft"} maxLength={200} value={draft.subject} onChange={(event) => setDraft({ ...draft, subject: event.target.value })}/></label><label>PLAIN-TEXT BODY<textarea disabled={!canAdmin || draft.status !== "draft"} rows={8} maxLength={10000} value={draft.body_text} onChange={(event) => setDraft({ ...draft, body_text: event.target.value })}/><small>An authenticated one-click unsubscribe link is appended to every recipient copy.</small></label></div>
        {draft.status === "draft" ? <section className="marketing-audience"><header><div><b>SELECT CONTACTS</b><small>{draft.contact_ids.length} / 25 selected</small></div><span>Only current opted-in + express consent survives freezing.</span></header>{contacts.map((contact) => { const eligible = contact.consent_status === "opted_in" && contact.consent_basis === "express"; return <label key={contact.id} className={eligible ? "eligible" : "ineligible"}><input type="checkbox" checked={selectedContacts.has(contact.id)} disabled={!canAdmin || !eligible} onChange={() => toggleContact(contact.id)}/><span><b>{[contact.first_name, contact.last_name].filter(Boolean).join(" ") || contact.email}</b><small>{contact.email}</small></span><mark>{eligible ? "EXPRESS OPT-IN" : `${contact.consent_status || "UNKNOWN"} · ${contact.consent_basis || "NO BASIS"}`}</mark></label>; })}{!contacts.length && <p>No Contacts are available.</p>}</section> : <section className="marketing-evidence"><header><b>FROZEN RECIPIENT EVIDENCE</b><small>Immutable V{latestVersion?.version || "—"}</small></header>{latestVersion && <div className="marketing-summary"><span><b>{latestVersion.exclusion_summary.selected}</b> selected</span><span><b>{latestVersion.exclusion_summary.eligible}</b> eligible</span><span><b>{latestVersion.exclusion_summary.excluded}</b> excluded</span></div>}<div className="marketing-recipient-list">{recipients.map((recipient) => <article key={recipient.id}><div><b>{recipient.email}</b><small>{recipient.first_name || ""} {recipient.last_name || ""}</small></div><mark>{recipient.status}</mark><span>{recipient.attempt_count} attempt{recipient.attempt_count === 1 ? "" : "s"}</span><small>{recipient.error || recipient.provider_email_id || "Awaiting action"}</small></article>)}</div></section>}
        <footer>{canAdmin && draft.status === "draft" && <><button disabled={Boolean(working)} onClick={() => void save()}>SAVE DRAFT</button><button disabled={Boolean(working) || !draft.contact_ids.length || !signing} onClick={() => void lifecycle("publish")}>{armed === "publish" ? "CONFIRM FREEZE RECIPIENTS" : "FREEZE RECIPIENTS"}</button></>}{canAdmin && draft.status === "ready" && <><button disabled={Boolean(working) || !connection} onClick={() => void lifecycle("launch")}>{armed === "launch" ? "CONFIRM SEND CAMPAIGN" : "SEND CAMPAIGN"}</button><button disabled={Boolean(working)} onClick={() => void lifecycle("cancel")}>{armed === "cancel" ? "CONFIRM CANCEL CAMPAIGN" : "CANCEL"}</button></>}{canAdmin && draft.status === "sending" && <button disabled={Boolean(working)} onClick={() => void lifecycle("cancel")}>{armed === "cancel" ? "CONFIRM CANCEL CAMPAIGN" : "CANCEL UNSENT"}</button>}{canAdmin && draft.status === "completed" && failed > 0 && <button disabled={Boolean(working)} onClick={() => void lifecycle("retry")}>{armed === "retry" ? "CONFIRM RETRY FAILED RECIPIENTS" : `RETRY ${failed} FAILED`}</button>}</footer>
      </> : <p>Select a campaign.</p>}</section></div>
  </main>;
}
