"use client";

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";

type Entry={id:string;contact_id:string|null;opportunity_id:string|null;parent_entry_id:string|null;kind:"payment"|"refund"|"dispute"|"dispute_reversal";amount_minor:number;currency:string;description:string;provider:string;provider_reference:string|null;occurred_at:string;created_by:string;created_at:string;contact_email?:string|null;contact_name?:string|null;opportunity_name?:string|null};
type Ledger={entries:Entry[];balances:Array<{currency:string;net_minor:number;gross_minor:number;refunded_minor:number;disputed_minor:number}>;links:{contacts:Array<{id:string;email:string;first_name:string|null;last_name:string|null}>;opportunities:Array<{id:string;contact_id:string;name:string;currency:string}>};truncated:boolean;provider_boundary:{mode:string;external_providers:boolean};accounting:{amounts:string;model:string;currency_conversion:boolean}};
type Draft={amount:string;currency:string;description:string;occurred_at:string;contact_id:string;opportunity_id:string;provider_reference:string};
const blank=(currency="USD"):Draft=>({amount:"",currency,description:"",occurred_at:new Date().toISOString().slice(0,16),contact_id:"",opportunity_id:"",provider_reference:""});
const minor=(value:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(value)||Number(value)<=0)throw new Error("Enter a positive amount with no more than two decimals");const [whole,fraction=""]=value.split(".");const result=Number(whole)*100+Number(fraction.padEnd(2,"0"));if(!Number.isSafeInteger(result))throw new Error("Amount is too large");return result;};
const format=(value:number,currency:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency}).format(value/100);
const signed=(entry:Entry)=>entry.kind==="payment"||entry.kind==="dispute_reversal"?entry.amount_minor:-entry.amount_minor;
const label=(entry:Entry)=>entry.kind.replaceAll("_"," ").toUpperCase();

export default function PaymentsWorkspace({active}:{active:boolean}){
  const [data,setData]=useState<Ledger|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(false),[currency,setCurrency]=useState("");
  const [draft,setDraft]=useState<Draft>(()=>blank()),[armed,setArmed]=useState(false),[saving,setSaving]=useState(false);
  const [selectedPayment,setSelectedPayment]=useState<Entry|null>(null),[adjustKind,setAdjustKind]=useState<"refund"|"dispute"|"dispute_reversal">("refund"),[adjust,setAdjust]=useState<Draft>(()=>blank());
  const pendingIdempotencyKey=useRef("");
  const load=useCallback(async(filter=currency)=>{setLoading(true);setError("");try{const response=await fetch(`/v1/admin/payments/ledger${filter?`?currency=${encodeURIComponent(filter)}`:""}`,{credentials:"include"});const body=await response.json() as Ledger&{error?:string};if(!response.ok)throw new Error(body.error||`Ledger failed (${response.status})`);setData(body);}catch(cause){setError(cause instanceof Error?cause.message:"Ledger could not be loaded");}finally{setLoading(false);}},[currency]);
  useEffect(()=>{if(!active)return;const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[active,load]);
  const paymentById=useMemo(()=>new Map((data?.entries||[]).filter((entry)=>entry.kind==="payment").map((entry)=>[entry.id,entry])),[data]);
  const post=async(url:string,body:Record<string,unknown>)=>{const response=await fetch(url,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as {error?:string;duplicate?:boolean};if(!response.ok)throw new Error(result.error||`Request failed (${response.status})`);return result;};
  const record=async(event:FormEvent)=>{event.preventDefault();if(!armed){pendingIdempotencyKey.current=crypto.randomUUID();setArmed(true);return;}setSaving(true);setError("");try{await post("/v1/admin/payments/ledger",{contact_id:draft.contact_id||undefined,opportunity_id:draft.opportunity_id||undefined,amount_minor:minor(draft.amount),currency:draft.currency.toUpperCase(),description:draft.description,occurred_at:new Date(draft.occurred_at).toISOString(),provider_reference:draft.provider_reference||undefined,idempotency_key:pendingIdempotencyKey.current,confirmation:"RECORD PAYMENT"});setDraft(blank(draft.currency));setArmed(false);pendingIdempotencyKey.current="";setNotice("Payment recorded as an immutable ledger event.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Payment could not be recorded");}finally{setSaving(false);}};
  const recordAdjustment=async(event:FormEvent)=>{event.preventDefault();if(!selectedPayment)return;if(!armed){pendingIdempotencyKey.current=crypto.randomUUID();setArmed(true);return;}setSaving(true);setError("");try{await post(`/v1/admin/payments/ledger/${selectedPayment.id}/adjustments`,{kind:adjustKind,amount_minor:minor(adjust.amount),currency:selectedPayment.currency,description:adjust.description,occurred_at:new Date(adjust.occurred_at).toISOString(),provider_reference:adjust.provider_reference||undefined,idempotency_key:pendingIdempotencyKey.current,confirmation:`RECORD ${adjustKind.replace("_"," ").toUpperCase()}`});setSelectedPayment(null);setAdjust(blank(selectedPayment.currency));setArmed(false);pendingIdempotencyKey.current="";setNotice(`${label({...selectedPayment,kind:adjustKind} as Entry)} recorded as a linked event.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Adjustment could not be recorded");}finally{setSaving(false);}};
  if(!active)return null;
  return <main className="payments-workspace"><header className="payments-hero"><div><p>MANUAL CASH REGISTER</p><h1>Payments</h1><p>Record money events without pretending a processor is connected. Entries are permanent; corrections are explicit linked adjustments.</p></div><button onClick={()=>void load()} disabled={loading}>{loading?"SYNCING…":"REFRESH REGISTER"}</button></header>
    <section className="payment-boundary"><b>MANUAL MODE</b><span>No Stripe, bank, payout, invoice, or settlement synchronization is active.</span><small>Amounts stay in their original currency. No FX conversion.</small></section>
    {error&&<div className="conversation-banner error" role="alert">{error}</div>}{notice&&<div className="conversation-banner" role="status">{notice}</div>}
    <section className="payment-balances" aria-label="Ledger balances">{data?.balances.length?data.balances.map((row)=><article key={row.currency}><small>{row.currency} NET COLLECTED</small><strong>{format(Number(row.net_minor),row.currency)}</strong><dl><div><dt>GROSS</dt><dd>{format(Number(row.gross_minor),row.currency)}</dd></div><div><dt>REFUNDED</dt><dd>{format(Number(row.refunded_minor),row.currency)}</dd></div><div><dt>IN DISPUTE</dt><dd>{format(Number(row.disputed_minor),row.currency)}</dd></div></dl></article>):<article className="payment-zero"><small>REGISTER EMPTY</small><strong>Record the first verified payment.</strong></article>}</section>
    <div className="payments-layout"><section className="payment-register"><header><div><p>EVENT TAPE</p><h2>Append-only ledger</h2></div><label>CURRENCY<select value={currency} onChange={(event)=>{setCurrency(event.target.value);void load(event.target.value);}}><option value="">ALL</option>{Array.from(new Set(data?.balances.map((row)=>row.currency)||[])).map((code)=><option key={code}>{code}</option>)}</select></label></header>
      <div className="payment-tape">{data?.entries.length?data.entries.map((entry)=><article key={entry.id} className={entry.kind}><time>{new Date(entry.occurred_at).toLocaleString()}</time><i/><div><span>{label(entry)}</span><strong>{entry.description}</strong><small>{entry.opportunity_name||entry.contact_name||entry.contact_email||"Linked record"} · {entry.provider_reference||entry.id.slice(-10)}</small>{entry.parent_entry_id&&<small>Adjusts {paymentById.get(entry.parent_entry_id)?.description||"original payment"}</small>}</div><b>{signed(entry)>0?"+":"−"}{format(Math.abs(signed(entry)),entry.currency)}</b>{entry.kind==="payment"&&<button type="button" onClick={()=>{setSelectedPayment(entry);setAdjust(blank(entry.currency));setArmed(false);setNotice("");}}>ADJUST</button>}</article>):<div className="payment-empty">No ledger events match this register.</div>}</div>{data?.truncated&&<small className="payment-truncated">Showing the latest 500 events.</small>}</section>
      <aside className="payment-entry"><p>NEW EVENT</p>{selectedPayment?<form onSubmit={recordAdjustment}><h2>Adjust payment</h2><small>{selectedPayment.description} · {format(selectedPayment.amount_minor,selectedPayment.currency)}</small><label>EVENT TYPE<select value={adjustKind} onChange={(e)=>{setAdjustKind(e.target.value as typeof adjustKind);setArmed(false);}}><option value="refund">Refund</option><option value="dispute">Dispute</option><option value="dispute_reversal">Dispute reversal</option></select></label><MoneyFields value={adjust} onChange={(next)=>{setAdjust(next);setArmed(false);}} currencyLocked/><div className="payment-actions"><button disabled={saving}>{saving?"RECORDING…":armed?`CONFIRM RECORD ${adjustKind.replace("_"," ").toUpperCase()}`:"REVIEW ADJUSTMENT"}</button><button type="button" className="secondary" onClick={()=>{setSelectedPayment(null);setArmed(false);}}>CANCEL</button></div>{armed&&<small className="payment-warning">This appends a permanent event. The original payment will not be edited.</small>}</form>:<form onSubmit={record}><h2>Record payment</h2><label>OPPORTUNITY<select value={draft.opportunity_id} onChange={(e)=>{const opportunity=data?.links.opportunities.find((row)=>row.id===e.target.value);setDraft({...draft,opportunity_id:e.target.value,contact_id:opportunity?.contact_id||draft.contact_id,currency:opportunity?.currency||draft.currency});setArmed(false);}}><option value="">None</option>{data?.links.opportunities.map((row)=><option key={row.id} value={row.id}>{row.name} · {row.currency}</option>)}</select></label><label>CONTACT<select required={!draft.opportunity_id} value={draft.contact_id} onChange={(e)=>{setDraft({...draft,contact_id:e.target.value,opportunity_id:""});setArmed(false);}}><option value="">Select contact</option>{data?.links.contacts.map((row)=><option key={row.id} value={row.id}>{[row.first_name,row.last_name].filter(Boolean).join(" ")||row.email} · {row.email}</option>)}</select></label><MoneyFields value={draft} onChange={(next)=>{setDraft(next);setArmed(false);}}/><div className="payment-actions"><button disabled={saving}>{saving?"RECORDING…":armed?"CONFIRM RECORD PAYMENT":"REVIEW PAYMENT"}</button></div>{armed&&<small className="payment-warning">Confirm only after verifying the money was received outside this CRM.</small>}</form>}</aside></div>
  </main>;
}

function MoneyFields({value,onChange,currencyLocked=false}:{value:Draft;onChange:(value:Draft)=>void;currencyLocked?:boolean}){return <><div className="money-row"><label>AMOUNT<input required inputMode="decimal" placeholder="0.00" value={value.amount} onChange={(e)=>onChange({...value,amount:e.target.value})}/></label><label>CURRENCY<input required disabled={currencyLocked} maxLength={3} pattern="[A-Za-z]{3}" value={value.currency} onChange={(e)=>onChange({...value,currency:e.target.value.toUpperCase()})}/></label></div><label>DESCRIPTION<input required maxLength={240} value={value.description} onChange={(e)=>onChange({...value,description:e.target.value})} placeholder="What was paid for?"/></label><label>OCCURRED AT<input required type="datetime-local" value={value.occurred_at} onChange={(e)=>onChange({...value,occurred_at:e.target.value})}/></label><label>REFERENCE <small>OPTIONAL</small><input maxLength={160} value={value.provider_reference} onChange={(e)=>onChange({...value,provider_reference:e.target.value})} placeholder="Receipt or transfer reference"/></label></>}
