"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Report={range:{preset:string;start:string;end_exclusive:string;timezone:string};permissions:{contacts:boolean;opportunities:boolean};summary:{new_contacts:number;current_customers:number;opportunities?:number;open_opportunities?:number;current_won?:number;current_lost?:number};values_by_currency:Array<{currency:string;open_value:number;current_won_value:number}>|null;daily:Array<{day:string;contacts:number;current_customers:number;opportunities?:number;current_won?:number}>;lifecycle_distribution:Array<{stage:string;contacts:number}>;source_first_touch:{rows:Array<{source:string;contacts:number;current_customers:number;won_contacts?:number}>;truncated:boolean};pipeline_stage_snapshot:Array<{pipeline_id:string;pipeline_name:string;stage_id:string;stage_name:string;position:number;category:string;color:string;opportunities:number}>|null;methodology:{cohort:string;conversion:string;attribution:string;currency:string};generated_at:string};
async function getReport(query:string){const response=await fetch(`/v1/admin/reports/revenue-funnel?${query}`,{credentials:"include"});const body=await response.json() as Report&{error?:string};if(!response.ok)throw new Error(body.error||`Report failed (${response.status})`);return body;}
const number=(value:unknown)=>Number(value||0).toLocaleString("en-US");
const money=(value:unknown,currency:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value||0));

export default function ReportingWorkspace({active}:{active:boolean}){
  const [preset,setPreset]=useState("30"),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  const load=useCallback(async(value:string)=>{setLoading(true);setError("");try{setReport(await getReport(`preset=${value}`));}catch(cause){setError(cause instanceof Error?cause.message:"Report could not be loaded");}finally{setLoading(false);}},[]);
  useEffect(()=>{if(!active)return;const timer=setTimeout(()=>void load(preset),0);return()=>clearTimeout(timer);},[active,load,preset]);
  const maxDaily=useMemo(()=>Math.max(1,...(report?.daily.map((row)=>Number(row.contacts)+Number(row.opportunities||0))||[])),[report]);
  const maxLifecycle=useMemo(()=>Math.max(1,...(report?.lifecycle_distribution.map((row)=>Number(row.contacts))||[])),[report]);
  if(!active)return null;
  return <main className="report-workspace"><header className="report-hero"><div><p>FIRST-PARTY SIGNAL BOOK</p><h1>Reports</h1><p>Read the records your CRM actually holds. Every number below is scoped, dated, and labeled by what it can prove.</p></div><div className="report-range" aria-label="Report range">{["7","30","90"].map((value)=><button key={value} className={preset===value?"active":""} aria-pressed={preset===value} onClick={()=>setPreset(value)}>{value} DAYS</button>)}</div></header>
    {error&&<div className="conversation-banner error" role="alert">{error}</div>}
    {loading&&!report?<div className="report-loading">CALCULATING COHORT…</div>:report&&<>
      <section className="report-contract"><span>COHORT</span><b>{new Date(report.range.start).toLocaleDateString()} → {new Date(Date.parse(report.range.end_exclusive)-1).toLocaleDateString()}</b><small>UTC · generated {new Date(report.generated_at).toLocaleTimeString()}</small></section>
      <section className="report-kpis" aria-label="Cohort summary"><article><small>NEW CONTACTS</small><strong>{number(report.summary.new_contacts)}</strong><span>created in range</span></article><article><small>CURRENT CUSTOMERS</small><strong>{number(report.summary.current_customers)}</strong><span>from this cohort now</span></article>{report.permissions.opportunities&&<><article><small>OPPORTUNITIES</small><strong>{number(report.summary.opportunities)}</strong><span>created in range</span></article><article><small>CURRENTLY WON</small><strong>{number(report.summary.current_won)}</strong><span>snapshot, not transition rate</span></article></>}</section>
      <div className="report-grid"><section className="report-panel report-tempo"><header><div><p>ARRIVAL TEMPO</p><h2>Records entering the system</h2></div><small>DAILY / UTC</small></header>{report.daily.length?<div className="tempo-chart">{report.daily.map((row)=><div className="tempo-column" key={row.day} title={`${row.day}: ${number(row.contacts)} contacts, ${number(row.opportunities)} opportunities`}><div><i style={{height:`${Math.max(2,Number(row.contacts)/maxDaily*100)}%`}}/><b style={{height:`${Number(row.opportunities||0)/maxDaily*100}%`}}/></div><time>{row.day.slice(5)}</time></div>)}</div>:<div className="report-empty">No contacts or opportunities entered during this range.</div>}<footer><span><i/> CONTACTS</span>{report.permissions.opportunities&&<span><b/> OPPORTUNITIES</span>}</footer></section>
        <section className="report-panel report-lifecycle"><header><div><p>CONTACT COHORT</p><h2>Current lifecycle distribution</h2></div></header>{report.lifecycle_distribution.length?<div>{report.lifecycle_distribution.map((row)=><article key={row.stage}><span>{row.stage.replaceAll("_"," ")}</span><i><b style={{width:`${Number(row.contacts)/maxLifecycle*100}%`}}/></i><strong>{number(row.contacts)}</strong></article>)}</div>:<div className="report-empty">No contacts entered during this range.</div>}</section></div>
      <section className="report-panel report-source"><header><div><p>DIRECTIONAL SOURCE VIEW</p><h2>First touch carried by the contact</h2></div><small>NOT CAUSAL ATTRIBUTION</small></header>{report.source_first_touch.rows.length?<div className="report-table"><div className="report-table-head"><span>SOURCE</span><span>CONTACTS</span><span>CUSTOMERS NOW</span>{report.permissions.opportunities&&<span>CONTACTS WITH A WIN</span>}</div>{report.source_first_touch.rows.map((row)=><article key={row.source}><strong>{row.source}</strong><span>{number(row.contacts)}</span><span>{number(row.current_customers)}</span>{report.permissions.opportunities&&<span>{number(row.won_contacts)}</span>}</article>)}</div>:<div className="report-empty">No first-touch source records exist in this cohort.</div>}</section>
      {report.permissions.opportunities&&<section className="report-panel report-pipeline"><header><div><p>PIPELINE SNAPSHOT</p><h2>Where this opportunity cohort sits now</h2></div><small>NOT HISTORICAL CONVERSION</small></header>{report.pipeline_stage_snapshot?.length?<div className="pipeline-report-groups">{Array.from(new Set(report.pipeline_stage_snapshot.map((row)=>row.pipeline_id))).map((pipelineId)=>{const rows=report.pipeline_stage_snapshot!.filter((row)=>row.pipeline_id===pipelineId);return <article key={pipelineId}><h3>{rows[0].pipeline_name}</h3><div>{rows.map((row)=><section key={row.stage_id}><i style={{background:row.color}}/><span>{row.stage_name}</span><strong>{number(row.opportunities)}</strong><small>{row.category}</small></section>)}</div></article>;})}</div>:<div className="report-empty">No active pipeline stages are available.</div>}</section>}
      {report.permissions.opportunities&&Boolean(report.values_by_currency?.length)&&<section className="report-values"><p>VALUE REGISTER</p>{report.values_by_currency!.map((row)=><article key={row.currency}><b>{row.currency}</b><span>Open {money(row.open_value,row.currency)}</span><span>Currently won {money(row.current_won_value,row.currency)}</span></article>)}</section>}
      <details className="report-method"><summary>How to read this report</summary><p>{report.methodology.cohort}</p><p>{report.methodology.conversion}</p><p>{report.methodology.attribution}</p><p>{report.methodology.currency}</p></details>
    </>}
  </main>;
}
