"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Component = { id: string; type: "hero" | "text" | "features" | "cta"; eyebrow?: string; heading: string; body?: string; cta_label?: string; cta_href?: string; items?: Array<{ title: string; body: string }> };
type Page = { id: string; path: string; title: string; description: string; components: Component[] };
type Site = { id: string; name: string; slug: string; status: "draft" | "published" | "revoked"; pages: Page[]; theme: { background: string; surface: string; text: string; accent: string; font: "system" | "serif" | "mono" }; custom_domain: null; domain_status: "disabled"; revision: number; public_path: string | null; version_count?: number };
async function api<T>(path: string, init?: RequestInit) { const response = await fetch(path, { credentials: "include", ...init }); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; }
const componentDefault = (type: Component["type"], index: number): Component => type === "hero" ? { id: `hero_${index}`, type, eyebrow: "NEW", heading: "A clear headline", body: "Explain the outcome your visitor wants.", cta_label: "Learn more", cta_href: "#details" } : type === "features" ? { id: `features_${index}`, type, heading: "Why it matters", items: [{ title: "First benefit", body: "Explain the value." }, { title: "Second benefit", body: "Add proof or detail." }] } : type === "cta" ? { id: `cta_${index}`, type, heading: "Take the next step", body: "Tell visitors what happens next.", cta_label: "Get started", cta_href: "/" } : { id: `text_${index}`, type, heading: "Section heading", body: "Write the details here." };

export default function SitesWorkspace({ active, canAdmin }: { active: boolean; canAdmin: boolean }) {
  const [sites, setSites] = useState<Site[]>([]), [selectedId, setSelectedId] = useState(""), [draft, setDraft] = useState<Site | null>(null), [pageId, setPageId] = useState(""), [creating, setCreating] = useState(false), [name, setName] = useState(""), [working, setWorking] = useState(""), [armed, setArmed] = useState(""), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const selected = useMemo(() => sites.find((site) => site.id === selectedId), [sites, selectedId]); const page = draft?.pages.find((candidate) => candidate.id === pageId) || draft?.pages[0];
  const load = useCallback(async () => { const data = await api<{ sites: Site[] }>("/v1/admin/sites"); setSites(data.sites); setSelectedId((current) => current && data.sites.some((site) => site.id === current) ? current : data.sites[0]?.id || ""); }, []);
  useEffect(() => { if (!active) return; const timer = setTimeout(() => void load().catch((cause) => setError(cause.message)), 0); return () => clearTimeout(timer); }, [active, load]);
  useEffect(() => { if (!active || !selectedId) return; let cancelled = false; void api<{ site: Site }>(`/v1/admin/sites/${selectedId}`).then((data) => { if (!cancelled) { setDraft(data.site); setPageId((current) => data.site.pages.some((candidate) => candidate.id === current) ? current : data.site.pages[0].id); } }).catch((cause) => { if (!cancelled) setError(cause.message); }); return () => { cancelled = true; }; }, [active, selectedId]);
  async function create(event: FormEvent) { event.preventDefault(); setWorking("create"); setError(""); try { const data = await api<{ site: Site }>("/v1/admin/sites", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }) }); setCreating(false); setName(""); await load(); setSelectedId(data.site.id); setNotice("Site draft created on an OpenOperator hosted path."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Site could not be created"); } finally { setWorking(""); } }
  async function save() { if (!draft) return; setWorking("save"); setError(""); try { const data = await api<{ site: Site }>(`/v1/admin/sites/${draft.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: draft.name, pages: draft.pages, theme: draft.theme, if_revision: draft.revision }) }); setDraft(data.site); await load(); setNotice("Draft saved. Published pages did not change."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Site could not be saved"); } finally { setWorking(""); } }
  async function lifecycle(action: "publish" | "revoke") { if (!draft) return; if (armed !== action) { setArmed(action); return; } setWorking(action); setError(""); try { const data = await api<{ site: Site }>(`/v1/admin/sites/${draft.id}/${action}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ if_revision: draft.revision, confirmation: action === "publish" ? "PUBLISH SITE" : "REVOKE SITE" }) }); setDraft(data.site); setArmed(""); await load(); setNotice(action === "publish" ? "Published as a new immutable site version." : "Hosted site access revoked."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Site lifecycle failed"); } finally { setWorking(""); } }
  function updatePage(patch: Partial<Page>) { if (draft && page) setDraft({ ...draft, pages: draft.pages.map((candidate) => candidate.id === page.id ? { ...candidate, ...patch } : candidate) }); }
  function updateComponent(index: number, patch: Partial<Component>) { if (page) updatePage({ components: page.components.map((component, position) => position === index ? { ...component, ...patch } : component) }); }
  function moveComponent(index: number, direction: -1 | 1) { if (!page) return; const target = index + direction; if (target < 0 || target >= page.components.length) return; const components = [...page.components]; [components[index], components[target]] = [components[target], components[index]]; updatePage({ components }); }
  if (!active) return null;
  return <main className="sites-workspace"><header className="sites-hero"><div><p>BOUNDED PUBLISHING SYSTEM</p><h1>Sites</h1><span>Compose safe pages, freeze each publication, and host them on an OpenOperator path. No arbitrary code or custom-domain routing is active.</span></div>{canAdmin && <button onClick={() => setCreating(true)}>NEW SITE</button>}</header>{error && <div className="conversation-banner error">{error}</div>}{notice && <div className="conversation-banner">{notice}</div>}
    {creating && <form className="site-create" onSubmit={create}><label>INTERNAL SITE NAME<input required value={name} onChange={(event) => setName(event.target.value)}/></label><button disabled={working === "create"}>CREATE HOSTED DRAFT</button><button type="button" onClick={() => setCreating(false)}>CANCEL</button></form>}
    <div className="sites-layout"><aside className="site-register"><header><b>SITE REGISTER</b><small>{sites.length} total</small></header>{sites.map((site) => <button key={site.id} className={site.id === selectedId ? "active" : ""} onClick={() => setSelectedId(site.id)}><b>{site.name}</b><span>{site.status} · {site.version_count || 0} versions</span></button>)}{!sites.length && <p>No hosted sites yet.</p>}</aside>
      <section className="site-studio">{draft && selected && page ? <><header><div><p>HOSTED / {draft.slug}</p><h2>{draft.name}</h2></div><mark>{draft.status}</mark></header><div className="site-boundary"><b>HOSTING BOUNDARY</b><span>OpenOperator path only</span><small>Custom domain, scripts, uploads, CSS injection, and analytics injection are disabled.</small></div>
        <div className="site-settings"><label>INTERNAL NAME<input disabled={!canAdmin} value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })}/></label><label>FONT<select disabled={!canAdmin} value={draft.theme.font} onChange={(event) => setDraft({ ...draft, theme: { ...draft.theme, font: event.target.value as Site["theme"]["font"] } })}>{["system", "serif", "mono"].map((font) => <option key={font}>{font}</option>)}</select></label>{(["background", "surface", "text", "accent"] as const).map((color) => <label key={color}>{color.toUpperCase()}<input disabled={!canAdmin} type="color" value={draft.theme[color]} onChange={(event) => setDraft({ ...draft, theme: { ...draft.theme, [color]: event.target.value } })}/></label>)}</div>
        <nav className="site-page-tabs" aria-label="Site pages">{draft.pages.map((candidate) => <button key={candidate.id} className={candidate.id === page.id ? "active" : ""} onClick={() => setPageId(candidate.id)}>{candidate.title}<small>{candidate.path}</small></button>)}{canAdmin && draft.pages.length < 10 && <button onClick={() => { const index = draft.pages.length + 1; const next: Page = { id: `page_${index}`, path: `/page-${index}`, title: `Page ${index}`, description: "", components: [componentDefault("text", 1)] }; setDraft({ ...draft, pages: [...draft.pages, next] }); setPageId(next.id); }}>+ PAGE</button>}</nav>
        <div className="site-page-meta"><label>PAGE TITLE<input disabled={!canAdmin} value={page.title} onChange={(event) => updatePage({ title: event.target.value })}/></label><label>PATH<input disabled={!canAdmin || page.path === "/"} value={page.path} onChange={(event) => updatePage({ path: event.target.value.toLowerCase().replace(/[^a-z0-9/-]/g, "-") })}/></label><label>SEO DESCRIPTION<textarea disabled={!canAdmin} value={page.description} onChange={(event) => updatePage({ description: event.target.value })}/></label>{canAdmin && draft.pages.length > 1 && page.path !== "/" && <button onClick={() => { const remaining = draft.pages.filter((candidate) => candidate.id !== page.id); setDraft({ ...draft, pages: remaining }); setPageId(remaining[0].id); }}>REMOVE PAGE</button>}</div>
        <div className="site-component-list"><header><b>ORDERED COMPONENTS</b><div>{canAdmin && (["hero", "text", "features", "cta"] as Component["type"][]).map((type) => <button key={type} onClick={() => updatePage({ components: [...page.components, componentDefault(type, page.components.length + 1)] })}>+ {type}</button>)}</div></header>{page.components.map((component, index) => <article key={`${component.id}:${index}`}><header><span>{String(index + 1).padStart(2, "0")}</span><b>{component.type}</b><label>STABLE ID<input disabled={!canAdmin} value={component.id} onChange={(event) => updateComponent(index, { id: event.target.value.toLowerCase().replace(/[^a-z0-9_]/g, "_") })}/></label>{canAdmin && <div><button disabled={index === 0} onClick={() => moveComponent(index, -1)}>↑</button><button disabled={index === page.components.length - 1} onClick={() => moveComponent(index, 1)}>↓</button><button disabled={page.components.length === 1} onClick={() => updatePage({ components: page.components.filter((_, position) => position !== index) })}>REMOVE</button></div>}</header>{component.type === "hero" && <label>EYEBROW<input disabled={!canAdmin} value={component.eyebrow || ""} onChange={(event) => updateComponent(index, { eyebrow: event.target.value })}/></label>}<label>HEADING<input disabled={!canAdmin} value={component.heading} onChange={(event) => updateComponent(index, { heading: event.target.value })}/></label>{component.type !== "features" && <label>BODY<textarea disabled={!canAdmin} value={component.body || ""} onChange={(event) => updateComponent(index, { body: event.target.value })}/></label>}{component.type === "features" && <label>FEATURES · TITLE | BODY<textarea disabled={!canAdmin} value={(component.items || []).map((item) => `${item.title} | ${item.body}`).join("\n")} onChange={(event) => updateComponent(index, { items: event.target.value.split("\n").filter(Boolean).map((line) => { const [title, ...body] = line.split("|"); return { title: title.trim(), body: body.join("|").trim() }; }) })}/></label>}{["hero", "cta"].includes(component.type) && <div className="site-action-fields"><label>BUTTON LABEL<input disabled={!canAdmin} value={component.cta_label || ""} onChange={(event) => updateComponent(index, { cta_label: event.target.value })}/></label><label>RELATIVE OR HTTPS LINK<input disabled={!canAdmin} value={component.cta_href || ""} onChange={(event) => updateComponent(index, { cta_href: event.target.value })}/></label></div>}</article>)}</div>
        <footer>{canAdmin && <><button disabled={Boolean(working)} onClick={() => void save()}>SAVE DRAFT</button><button disabled={Boolean(working)} onClick={() => void lifecycle("publish")}>{armed === "publish" ? "CONFIRM PUBLISH SITE" : "PUBLISH"}</button>{draft.status === "published" && <button disabled={Boolean(working)} onClick={() => void lifecycle("revoke")}>{armed === "revoke" ? "CONFIRM REVOKE SITE" : "REVOKE"}</button>}</>}{draft.public_path && <a href={draft.public_path} target="_blank">OPEN PUBLISHED SITE ↗</a>}</footer>
      </> : <p>Select a site.</p>}</section>
    </div></main>;
}
